source 'https://github.com/CocoaPods/Specs.git'

target 'RasterPrint', :exclusive => true do
  pod "RasterPrint", :path => "../"
  pod "RasterPrint/Reactive", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RasterPrint", :path => "../"
  pod 'Kiwi'
end
